# Numpy Tutorial

Tutorial muito introdutório do Numpy. Serão abordados os seguintes tópicos:
1. [Importação](#1)
2. [Criação de ndarrays](#2)
3. [Atributos dos ndarrays](#3)
4. [Indexing & Slicing](#4)

Baseado no tutorial da TutorialsPoint: https://www.tutorialspoint.com/numpy/index.htm

## <a name="1">1. Importar o Numpy</a>

In [4]:
import numpy as np

## <a name="2">2. Criação de ndarrays</a>

In [2]:
# ndarray 1D
print(np.array([1, 2, 3]))

[1 2 3]


In [3]:
# ndarray 1D através de list comprehensions
print(np.array([i for i in range(10)]))

[0 1 2 3 4 5 6 7 8 9]


In [5]:
# ndarray 1D com definição do tipo dos dados
print(np.array([1, 2, 3], dtype=complex))

[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# ndarray 2D vazio de tipo inteiro
# na realidade é preenchido com valores aleatórios
print(np.empty([3,2], dtype = int))

[[4607182418800017408                   0]
 [4611686018427387904                   0]
 [4613937818241073152                   0]]


In [7]:
# ndarray 1D inicializado com zeros (0)
print(np.zeros((5), dtype = np.int))

[0 0 0 0 0]


In [8]:
# ndarray 2D inicializado com uns (1)
print(np.ones([2,2], dtype = int))

[[1 1]
 [1 1]]


In [9]:
# ndarray 1D linear entre 10 e 20 (exclusivé), de 2 em 2
print(np.arange(10, 20, 2))

[10 12 14 16 18]


In [10]:
# ndarray 1D igualmente espaçado entre 10 e 20 (inclusivé),
# com 5 valores
print(np.linspace(10, 20, 5))

[10.  12.5 15.  17.5 20. ]


In [14]:
# ndarray 1D, escala logarítimica de base 2, 
# com 10 valores
print(np.logspace(1,10,num=10,base=2))

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


## <a name="3">3. Atributos dos ndarrays</a>

In [17]:
arr = np.array([[1,2,3],[4,5,6]])

# shape – N.º de dados por dimensão do array
print('shape: {}'.format(arr.shape))

# ndim – N.º de dimensões
print('ndim: {}'.format(arr.ndim))

shape: (2, 3)
ndim: 2


## <a name="4">4. Indexing & Slicing</a>

In [18]:
a = np.arange(10) 
print(a[5]) # valor único
print(a[2:]) # intervalo 2 ao final
print(a[2:5]) # intervalo 2-4
print(a[2:7:2]) # intervalo 2-6, de 2 em 2

5
[2 3 4 5 6 7 8 9]
[2 3 4]
[2 4 6]


In [24]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(a)
print('\n')
print(a[1:]) # intervalo 1 ao final
print('\n')
print(a[...,1]) # Seleccionar coluna

[[1 2 3]
 [3 4 5]
 [4 5 6]]


[[3 4 5]
 [4 5 6]]


[2 4 5]


## 5. Documentação das funções

In [27]:
# Consultar documentacao de funções
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'